@Okala.CryptoExchange.WebApi_HostAddress = http://localhost:5168


GET {{Okala.CryptoExchange.WebApi_HostAddress}}/api/CryptoExChange/quote?symbol=BTC&convertSymbols=USD,EUR,BRL,GBP,AUD
Accept: application/json
Authorization: Bearer {{jwtToken}}
###

### Create JWT Token 
POST {{Okala.CryptoExchange.WebApi_HostAddress}}/api/Identity/createToken 
Content-Type:application/json